#!/bin/sh

HOTBM=`dirname $0`/../hotbm

# $1 = good file
# $2 = function
# $3 = input precision
# $4 = output precision
# $5 = polinomial size
do_test()
{
    TESTFILE=`dirname $0`/$1
    OUTFILE=/tmp/dotests.$$.$2_$3_$4_$5.vhdl
    DIFFFILE=/tmp/dotests.$$.diff

    echo -n "Testing $1 "
    BUILD=`/bin/echo -e "explore $2 $3 $4 $5\nquit" | $HOTBM 2>&1 | grep Best | cut -c 14-`
    echo -n "."
    /bin/echo -e "build $2 $BUILD\ngen $2_$3_$4_$5 $OUTFILE\nquit" | $HOTBM 2>/dev/null >/dev/null
    echo -n "."
    diff -u $OUTFILE $TESTFILE > $DIFFFILE
    if [ $? = 0 ]; then
	echo ". [32mPASS[0m"
    else
	echo ". [31mFAIL[0m"
	cat $DIFFFILE
    fi
    rm $OUTFILE
}

do_test sin_8_8_2.vhdl.good sin 8 8 2
do_test log_8_8_1.vhdl.good log 8 8 1
do_test sin_8_8_1.vhdl.good sin 8 8 1
do_test log_8_8_2.vhdl.good log 8 8 2
do_test sin_8_8_2.vhdl.good sin 8 8 2
do_test log_16_16_1.vhdl.good log 16 16 1
do_test sin_16_16_1.vhdl.good sin 16 16 1
do_test log_16_16_2.vhdl.good log 16 16 2
do_test sin_16_16_2.vhdl.good sin 16 16 2
